#!/usr/bin/env bash
set -e

usage() {
	cat <<EOF

Usage:
  gh arm <number>

Options:
  <number>    PR number to merge
EOF
}

pull_request_number=""

# Parse arguments
while [ "${1:-}" != "" ]; do
	case "$1" in
	# Matches every non-integer argument, including -h and --help
	*[!0-9]*)
		usage
		exit 1
		;;
	# A valid integer argument
	*)
		pull_request_number=$1
		shift # past value
		;;
	esac
done

gh pr merge --auto --merge "$pull_request_number"
gh pr ready "$pull_request_number"
